name: banana
summary: Banana Accounting Software
description: Excel-like, professional accounting software
confinement: strict
grade: stable
version: latest
# version-script: |
#   export LD_LIBRARY_PATH=$SNAPCRAFT_PRIME/usr/lib:$LD_LIBRARY_PATH
#   export QML_IMPORT_PATH=$SNAPCRAFT_PRIME/usr/qml
#   export QML2_IMPORT_PATH=$SNAPCRAFT_PRIME/usr/qml
#   export QT_QPA_PLATFORM_PLUGIN_PATH=$SNAPCRAFT_PRIME/usr/plugins
#   export QT_QPA_PLATFORMTHEME=qt5ct
#   $SNAPCRAFT_PRIME/usr/bin/bananaExperimental9 -cmd=version

architectures:
  - build-on: amd64
  - build-on: i386

apps:
  banana:
    environment:
      PATH: $PATH:$SNAP/bin
      LD_LIBRARY_PATH: $SNAP/usr/lib:$LD_LIBRARY_PATH
      QML_IMPORT_PATH: $SNAP/usr/qml
      QML2_IMPORT_PATH: $SNAP/usr/qml
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/plugins
      QT_QPA_PLATFORMTHEME: qt5ct
    command: desktop-launch $SNAP/usr/bin/bananaExperimental9
    desktop: bananaExperimental9.desktop
    plugs:
      - home
      - x11
      - unity7
      - wayland
      - desktop
      - desktop-legacy
      - opengl
      - removable-media
      - network
      - network-bind
      - network-manager
      - network-control
      - alsa
      - cups-control
      - gsettings

parts:
  banana:
    plugin: dump
    after: [desktop-glib-only]
    source: https://www.banana.ch/accounting/files/banana9/expm/bananaexpm9.tgz
    stage-packages:
      - libssl-dev
      - xdg-user-dirs
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - libegl1-mesa
      - libxcursor1
      - libnss3
      - libxcomposite1
      - libxi6
      - libxtst6
      - libasound2
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - shared-mime-info
      - libxkbcommon0
      - libxkbcommon-x11-0
      - light-themes
      - zlib1g
    override-pull: |
      snapcraftctl pull
      rm usr/lib/libssl.so
      rm usr/lib/libcrypto.so
    override-build: |
      sed -i 's|Icon=banico|Icon=${SNAP}/banico.svg|' $SNAPCRAFT_PART_BUILD/bananaExperimental9.desktop
      sed -i 's|Exec=.*|Exec=banana.banana|' $SNAPCRAFT_PART_BUILD/bananaExperimental9.desktop
      snapcraftctl build
    build-attributes: [no-system-libraries]

